# Copyright 2019, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-grafana

spec:
  storageClassName: grafana
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "%PV_ROOT%/monitoring/grafana"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-grafana
  namespace: monitoring

spec:
  storageClassName: grafana
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
